# Generated by Django 4.2.7 on 2023-11-23 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0002_director'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='poster',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
