# Generated by Django 4.2.7 on 2023-11-23 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0003_movies_poster'),
    ]

    operations = [
        migrations.CreateModel(
            name='CensorInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(max_length=50, null=True)),
                ('certified_by', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='movies',
            name='poster',
        ),
        migrations.AddField(
            model_name='movies',
            name='censor_details',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movie', to='app2.censorinfo'),
        ),
    ]
