# Generated by Django 4.2.7 on 2023-11-23 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0004_censorinfo_remove_movies_poster_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='directed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='directed_movie', to='app2.director'),
        ),
    ]
