# Generated by Django 4.2.7 on 2023-11-23 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0005_movies_directed_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='movies',
            name='actors',
            field=models.ManyToManyField(related_name='acted_movies', to='app2.actor'),
        ),
    ]
